name: build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: compile
        run: |
          deno task build:cli
          deno task build:browser
          zip -r dist/polka-browser.zip dist/polka-browser/

      - name: upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/polka
            dist/polka-browser.zip

